#!/bin/ash
TryCount=10
Interface="pppoe-wan"

MyName=${0##*/}
if [ $( ps | grep $MyName | wc -l) -gt 3 ]
then
echo "fucknat is already running"
exit 1
fi

echo -n "Testing connection to icanhazip.com..."
foo=$(wget -q --spider http://icanhazip.com)
if $foo
then
	echo "Online"
else
	echo "Offline"
	echo "Fucknat needs ethernet connection"
	exit $foo
fi

function TestNat
{
echo -n "Public ip is: "
PubIP=$(wget -q -4 -O- http://icanhazip.com)
echo $PubIP
echo -n "$Interface ip is: "
IfIP=$(ip addr show $Interface | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | grep -o [0-9].*)
echo $IfIP
if [[ $PubIP == $IfIP ]]
then
echo "Public ip detected"
Success
else
echo "Private ip detected"
fi
}

function Success
{
echo "Success: IP is public"
exit 0
}

function Fail
{
echo "Sorry, make this ip public is impossible"
#exit 1
}

TestNat


i=1
TryCount=$((TryCount + 1))
while [ $i -lt $TryCount ]
	do

	echo "Try $i"
	ifup -a $Interface
	until $(wget -q --spider http://icanhazip.com)
		do
		sleep 5
		done
	TestNat
	i=$((i + 1))
done

Fail

while true
do
sleep 1
done
